@baseUrl = http://localhost:3333

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlYWMxOGIyYS05NzY5LTQ0YzctYTkxNi0yOTk0MjViMGYyZDkiLCJpZCI6ImVhYzE4YjJhLTk3NjktNDRjNy1hOTE2LTI5OTQyNWIwZjJkOSIsIm5hbWUiOiJVc3VhcmlvIFRlc3RlIiwiZW1haWwiOiJ1c3VhcmlvQHRlc3RlLmNvbSIsInRva2VuVHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3OTExNTQ4MCwiZXhwIjoxNzc5MTI5ODgwfQ.8PfpzbDJCF5Hvo7JUNjw-8XeuqPJl0AvWoxVdt3hzUg

### [SUCESSO] Buscar usuário por ID existente
# Pré-requisito: ter ao menos um usuário criado para usar seu ID neste teste
# Esperado: 200 com objeto do usuário incluindo o campo slug
GET {{baseUrl}}/api/users
Authorization: Bearer {{accessToken}}

###

### [FALHA] Buscar usuário por ID inexistente
# Esperado: 404 NotFoundError com mensagem "Usuário não encontrado."
GET {{baseUrl}}/api/users

###
