@baseUrl = http://localhost:3333

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgQ2h1cGV0aW5oYSIsImVtYWlsIjoiYWJtYWVsQGVsZXRyaWNpc3RhLmNvbSIsInRva2VuVHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3ODY3MjEwNCwiZXhwIjoxNzc4Njg2NTA0fQ.Gc7-lZEQZ7i1sug5lZNEhWqM6rpkBXqHnQiN_kYhAmk

@scheduleIdAbmael = 2a8315a6-e1c8-452b-8881-d68f424a8d78
@scheduleIdAbmaelInexistente = gc3a020d-aad1-4950-9bf5-ba1865c5431h

### [SUCESSO] Remover horário existente
# Esperado: 204 sem corpo
DELETE {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessToken}}

###

### [FALHA] Tentar remover horário inexistente
# Esperado: 404 Not Found
DELETE {{baseUrl}}/api/schedules/{{scheduleIdAbmaelInexistente}}
Authorization: Bearer {{accessToken}}

### 

### [FALHA] Sem token de autenticação
# Esperado: 401 UnauthorizedError
DELETE {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}

###
