@baseUrl = http://localhost:3333

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgQ2h1cGV0aW5oYSIsImVtYWlsIjoiYWJtYWVsQGVsZXRyaWNpc3RhLmNvbSIsInRva2VuVHlwZSI6ImFjY2VzcyIsImlhdCI6MTc3ODY5MTYxNCwiZXhwIjoxNzc4NzA2MDE0fQ.-L2m9uLiftH7pmiFSgDx1YONLgpOcehD501fqEfDrks

@scheduleIdAbmael = 3187a57a-518b-4d9d-8b03-df03f12efe49
@scheduleIdAbmaelInexistente = gc3a020d-aad1-4950-9bf5-ba1865c5431h

### [SUCESSO] Buscar serviço por ID existente, de um usuario/prestador logado
# Pré-requisito: 
# 1) estar logado como usuario/prestador
# 2) ter ao menos um serviço criado
# Esperado: 200 com objeto do serviço incluindo price como número
GET {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessToken}}

###

### [FALHA] Buscar serviço por ID inexistente, de um usuario/prestador logado
# Pré-requisito: 
# 1) estar logado como usuario/prestador
# 2) passar um id de serviço inexistente
# Esperado: 400 - Bad Request com mensagem de erro "Service not found"
GET {{baseUrl}}/api/schedules/{{scheduleIdAbmaelInexistente}}
Authorization: Bearer {{accessToken}}

###

### [FALHA] Buscar serviço por ID existente, mas sem estar logado como usuario/prestador (sem token)
# Pré-requisito: 
# 1) ter ao menos um serviço criado
# 2) não estar logado como usuario/prestador (não fornecer token de acesso)
# Esperado: 401 - Unauthorized
GET {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}

###

### [FALHA] Tentar buscar serviço por ID inexistente, mas sem estar logado como usuario/prestador (sem token)
# Pré-requisito: 
# 1) passar um id de serviço inexistente
# 2) não estar logado como usuario/prestador (não fornecer token de acesso)
# Esperado: 401 - Unauthorized
GET {{baseUrl}}/api/schedules/{{scheduleIdAbmaelInexistente}}