@baseUrl = http://localhost:3333

@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjhlYWFjYS00N2I1LTRkZDItYjU4NC1kZjYwODZhMWM3NjUiLCJpZCI6IjNiOGVhYWNhLTQ3YjUtNGRkMi1iNTg0LWRmNjA4NmExYzc2NSIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkyODMzOTcsImV4cCI6MTc3OTI5Nzc5N30.zwqzrudYIhqogKywoKYhSPelBFhPB-39O7pcJhWSR3s

@scheduleIdAbmael = 5769ea74-8590-4ee8-ab47-56809c318af2
@scheduleIdAbmaelInexistente = gc3a020d-aad1-4950-9bf5-ba1865c5431h

### [FALHA] Sem token de autenticação
# Esperado: 401 UnauthorizedError
DELETE {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}

###

### [FALHA] Tentar remover horário inexistente
# Esperado: 404 Not Found
DELETE {{baseUrl}}/api/schedules/{{scheduleIdAbmaelInexistente}}
Authorization: Bearer {{accessTokenAbmael}}

###

### [SUCESSO] Remover horário existente
# Esperado: 204 sem corpo
DELETE {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}

### 
