@baseUrl = http://localhost:3333

@idUserAbmael = 3b8eaaca-47b5-4dd2-b584-df6086a1c765
@idUserCarlos = d48c3b6d-decd-41f7-8bd9-df2bf84f3cb1
@idUserInexistente = 7b89e3fc-16e6-45cd-ba9d-2e1dd076a179

### [SUCESSO] Listar serviços de um usuario/prestador existente
# Rota publica, não precisa de token
# Esperado: 200 com array de serviços do prestador
GET {{baseUrl}}/api/users/{{idUserAbmael}}/schedules

###

### [FALHA] Tentar Listar serviços de um usuario/prestador inexistente
# Rota publica, não precisa de token
# Esperado: 404 com mensagem de erro
GET {{baseUrl}}/api/users/{{idUserInexistente}}/schedules

###

### [FALHA] Tentar Listar serviços inexistente de um usuario/prestador existente
# Rota publica, não precisa de token
# Esperado: 404 com mensagem de erro
GET {{baseUrl}}/api/users/{{idUserCarlos}}/schedules
