@baseUrl = http://localhost:3333

@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjhlYWFjYS00N2I1LTRkZDItYjU4NC1kZjYwODZhMWM3NjUiLCJpZCI6IjNiOGVhYWNhLTQ3YjUtNGRkMi1iNTg0LWRmNjA4NmExYzc2NSIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkyODMzOTcsImV4cCI6MTc3OTI5Nzc5N30.zwqzrudYIhqogKywoKYhSPelBFhPB-39O7pcJhWSR3s

@scheduleIdAbmael = 5769ea74-8590-4ee8-ab47-56809c318af2
@scheduleIdAbmaelInexistente = gc3a020d-aad1-4950-9bf5-ba1865c5431h

### [FALHA] Sem token de autenticação
# Esperado: 401 UnauthorizedError
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "saturday",
  "startTime": "08:00",
  "endTime": "15:00",
  "isActive": true
}

###

### [FALHA] Atualizar horário inexistente
# Esperado: 400 BadRequestError
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmaelInexistente}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "saturday",
  "startTime": "07:30",
  "endTime": "17:30",
  "isActive": true
}

###

### [SUCESSO] Atualizar horário existente
# Esperado: 200 com horário atualizado
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "saturday",
  "startTime": "07:30",
  "endTime": "17:30",
  "isActive": true
}

###

### [FALHA] Atualização gera conflito com outro horário existente
# Esperado: 400 
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "monday",
  "startTime": "07:00",
  "endTime": "13:00",
  "isActive": true
}

###

### [FALHA] Atualização gera conflito com outro horário existente
# Esperado: 409 ConflictError
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "monday",
  "startTime": "10:00",
  "endTime": "16:00",
  "isActive": true
}

###

### [FALHA] dayOfWeek ausente no body
# Esperado: 422 Validation Error com campo dayOfWeek nos issues
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "startTime": "09:00",
  "endTime": "17:00",
  "isActive": true
}

###

### [FALHA] startTime >= endTime
# Esperado: 422 Validation Error com campo startTime nos issues
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "monday",
  "startTime": "17:00",
  "endTime": "09:00",
  "isActive": true
}

###

### [FALHA] startTime >= endTime
# Esperado: 422 Validation Error com campo IsActive nos issues
PUT {{baseUrl}}/api/schedules/{{scheduleIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "dayOfWeek": "monday",
  "startTime": "17:00",
  "endTime": "09:00"
}

###
