@baseUrl = http://localhost:3333

@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg1ODkwNDgsImV4cCI6MTc3ODYwMzQ0OH0._7mjfusoWuu7D-34yQpHyKLgl_cIZl9ES0I0-RuEatM

@accessTokenCarlos = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Yjg5ZTNmYy0xNmU2LTQ1Y2QtYmE5ZC0yZTFkZDA3NmExNzAiLCJpZCI6IjhiODllM2ZjLTE2ZTYtNDVjZC1iYTlkLTJlMWRkMDc2YTE3MCIsIm5hbWUiOiJDYXJsb3MgTGltYSIsImVtYWlsIjoiY2FybG9zQGxpbWEuY29tIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc4NTkxODM1LCJleHAiOjE3Nzg2MDYyMzV9.cjcMHKk0sTKmDDBP0MHtx9GYUKnShdBDH6Map2iA4Dw


### [SUCESSO] Listar todos os serviços de um usuário/prestador logado 
# Esperado: 200 com array de todos os serviços cadastrados
GET {{baseUrl}}/api/services
Authorization: Bearer {{accessTokenCarlos}}

###

### [FALHA] Não existe serviços cadastrados para o usuário/prestador logado 
# Esperado: 400 com mensagem de erro
GET {{baseUrl}}/api/services
Authorization: Bearer {{accessTokenCarlos}}
