@baseUrl = http://localhost:3333

@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjhlYWFjYS00N2I1LTRkZDItYjU4NC1kZjYwODZhMWM3NjUiLCJpZCI6IjNiOGVhYWNhLTQ3YjUtNGRkMi1iNTg0LWRmNjA4NmExYzc2NSIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkxOTMzNzIsImV4cCI6MTc3OTIwNzc3Mn0._P1-E0Mc5AGmpBhLiRHYbGORZO53S_ZS_5OPVBKsygY

@accessTokenCarlos = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MDk0MDIwNi0zMTkwLTQwNDAtYjcwYS01ZjMzYzdkNzBjY2UiLCJpZCI6IjQwOTQwMjA2LTMxOTAtNDA0MC1iNzBhLTVmMzNjN2Q3MGNjZSIsIm5hbWUiOiJDYXJsb3MgTGltYSIsImVtYWlsIjoiY2FybG9zQGxpbWEuY29tIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc4ODYwNTQxLCJleHAiOjE3Nzg4NzQ5NDF9.NmrFjxA72Z-LFDzaIY6eDZir0yr9XksB4PiAVWROdhE

@serviceIdAbmael = 6cbb928c-d45a-4992-b792-cd3dc1aaf48e
@serviceIdAbmaelInexistente = 39d8949c-6ca6-48bc-8b49-cc944b7ec05c

### [SUCESSO] Buscar serviço por ID existente, de um usuario/prestador logado
# Pré-requisito: 
# 1) estar logado como usuario/prestador
# 2) ter ao menos um serviço criado
# Esperado: 200 com objeto do serviço incluindo price como número
GET {{baseUrl}}/api/services/{{serviceIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}

###

### [FALHA] Buscar serviço por ID inexistente, de um usuario/prestador logado
# Pré-requisito: 
# 1) estar logado como usuario/prestador
# 2) passar um id de serviço inexistente
# Esperado: 400 - Bad Request com mensagem de erro "Service not found"
GET {{baseUrl}}/api/services/{{serviceIdAbmaelInexistente}}
Authorization: Bearer {{accessTokenAbmael}}

###

### [FALHA] Buscar serviço por ID existente, mas sem estar logado como usuario/prestador (sem token)
# Pré-requisito: 
# 1) ter ao menos um serviço criado
# 2) não estar logado como usuario/prestador (não fornecer token de acesso)
# Esperado: 401 - Unauthorized
GET {{baseUrl}}/api/services/{{serviceIdAbmael}}

###

### [FALHA] Tentar buscar serviço por ID inexistente, mas sem estar logado como usuario/prestador (sem token)
# Pré-requisito: 
# 1) passar um id de serviço inexistente
# 2) não estar logado como usuario/prestador (não fornecer token de acesso)
# Esperado: 401 - Unauthorized
GET {{baseUrl}}/api/services/{{serviceIdAbmaelInexistente}}