@baseUrl = http://localhost:3333
@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjhlYWFjYS00N2I1LTRkZDItYjU4NC1kZjYwODZhMWM3NjUiLCJpZCI6IjNiOGVhYWNhLTQ3YjUtNGRkMi1iNTg0LWRmNjA4NmExYzc2NSIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkxOTMzNzIsImV4cCI6MTc3OTIwNzc3Mn0._P1-E0Mc5AGmpBhLiRHYbGORZO53S_ZS_5OPVBKsygY

@accessTokenCarlos = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MDk0MDIwNi0zMTkwLTQwNDAtYjcwYS01ZjMzYzdkNzBjY2UiLCJpZCI6IjQwOTQwMjA2LTMxOTAtNDA0MC1iNzBhLTVmMzNjN2Q3MGNjZSIsIm5hbWUiOiJDYXJsb3MgTGltYSIsImVtYWlsIjoiY2FybG9zQGxpbWEuY29tIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc4ODYwNTQxLCJleHAiOjE3Nzg4NzQ5NDF9.NmrFjxA72Z-LFDzaIY6eDZir0yr9XksB4PiAVWROdhE

@serviceIdAbmael = 6cbb928c-d45a-4992-b792-cd3dc1aaf48e
@serviceIdAbmaelInexistente = 39d8949c-6ca6-48bc-8b49-cc944b7ec05c

### [FALHA] Sem token de autenticação
# Esperado: 401 UnauthorizedError
PUT {{baseUrl}}/api/services/{{serviceIdAbmael}}
Content-Type: application/json

{
  "name": "Teste de serviço atualizado",
  "description": "Serviço de teste atualizado",
  "durationMinutes": 10,
  "priceInCents": 100,
  "isActive": false
}

###

### [SUCESSO] Atualizar serviço com payload válido
# Pré-requisito: serviço com id = 1 deve existir
# Esperado: 200 com objeto do serviço atualizado
PUT {{baseUrl}}/api/services/{{serviceIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "name": "Teste de serviço atualizado",
  "description": "Serviço de teste atualizado",
  "durationMinutes": 10,
  "priceInCents": 100,
  "isActive": true
}

###

### [SUCESSO] Desativar serviço via atualização
# Esperado: 200 com isActive = false na resposta
PUT {{baseUrl}}/api/services/{{serviceIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "name": "Teste de serviço atualizado",
  "description": "Serviço de teste atualizado",
  "durationMinutes": 10,
  "priceInCents": 100,
  "isActive": false
}

###

### [FALHA] Atualizar serviço inexistente
# Esperado: 404 NotFoundError
PUT {{baseUrl}}/api/services/{{serviceIdAbmaelInexistente}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "name": "Instalação eletrica diversa",
  "description": "Serviço de instalação eletrica diversa",
  "durationMinutes": 60,
  "priceInCents": 10000,
  "isActive": true
}

###

### [FALHA] Campo obrigatório ausente (description)
# Esperado: 422 Validation Error com campo description nos issues
PUT {{baseUrl}}/api/services/{{serviceIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "name": "Teste de serviço atualizado",
  "description": "Serviço de teste atualizado",
  "durationMinutes": 10,
  "isActive": false
}

###

### [FALHA] durationMinutes inválido (negativo)
# Esperado: 422 Validation Error com campo durationMinutes nos issues
PUT {{baseUrl}}/api/services/{{serviceIdAbmael}}
Authorization: Bearer {{accessTokenAbmael}}
Content-Type: application/json

{
  "name": "Teste de serviço atualizado",
  "description": "Serviço de teste atualizado",
  "durationMinutes": -5,
  "priceInCents": 100,
  "isActive": false
}

###

### [FALHA] Servico valido de outro usuário, tentativa de atualização
# Esperado: 400 Bad Request com mensagem 
PUT {{baseUrl}}/api/services/{{serviceIdAbmael}}
Authorization: Bearer {{accessTokenCarlos}}
Content-Type: application/json

{
  "name": "Teste de serviço atualizado",
  "description": "Serviço de teste atualizado",
  "durationMinutes": 30,
  "priceInCents": 100,
  "isActive": false
}