@baseUrl = http://localhost:3333

@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYjhlYWFjYS00N2I1LTRkZDItYjU4NC1kZjYwODZhMWM3NjUiLCJpZCI6IjNiOGVhYWNhLTQ3YjUtNGRkMi1iNTg0LWRmNjA4NmExYzc2NSIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3NzkxOTMzNzIsImV4cCI6MTc3OTIwNzc3Mn0._P1-E0Mc5AGmpBhLiRHYbGORZO53S_ZS_5OPVBKsygY

@accessTokenCarlos = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MDk0MDIwNi0zMTkwLTQwNDAtYjcwYS01ZjMzYzdkNzBjY2UiLCJpZCI6IjQwOTQwMjA2LTMxOTAtNDA0MC1iNzBhLTVmMzNjN2Q3MGNjZSIsIm5hbWUiOiJDYXJsb3MgTGltYSIsImVtYWlsIjoiY2FybG9zQGxpbWEuY29tIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc4ODYwNTQxLCJleHAiOjE3Nzg4NzQ5NDF9.NmrFjxA72Z-LFDzaIY6eDZir0yr9XksB4PiAVWROdhE

### [SUCESSO] Listar todos os serviços de um usuário/prestador logado 
# Esperado: 200 com array de todos os serviços cadastrados
GET {{baseUrl}}/api/services/all
Authorization: Bearer {{accessTokenAbmael}}

###

### [FALHA] Não existe serviços cadastrados para o usuário/prestador logado 
# Esperado: 400 com mensagem de erro
GET {{baseUrl}}/api/services/all
Authorization: Bearer {{accessTokenCarlos}}

### [FALHA] Listar todos os serviços sem estar logado como usuario/prestador (sem token)
# Pré-requisito: 
# 1) ter ao menos um serviço criado
# 2) não estar logado como usuario/prestador (não fornecer token de acesso)
# Esperado: 401 - Unauthorized
GET {{baseUrl}}/api/services/all

###
