@baseUrl = http://localhost:3333

@accessTokenAbmael = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MjIyOThmOS1lZTBiLTQ5MzUtODU1Ni00YmIyYzVhMGRhOGEiLCJpZCI6IjQyMjI5OGY5LWVlMGItNDkzNS04NTU2LTRiYjJjNWEwZGE4YSIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg4NjA1MTksImV4cCI6MTc3ODg3NDkxOX0.I0-iPaYxMEZSADACvGNrG5iXWNe9t3voG26ovJxNchE

@accessTokenCarlos = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MDk0MDIwNi0zMTkwLTQwNDAtYjcwYS01ZjMzYzdkNzBjY2UiLCJpZCI6IjQwOTQwMjA2LTMxOTAtNDA0MC1iNzBhLTVmMzNjN2Q3MGNjZSIsIm5hbWUiOiJDYXJsb3MgTGltYSIsImVtYWlsIjoiY2FybG9zQGxpbWEuY29tIiwidG9rZW5UeXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc4ODYwNTQxLCJleHAiOjE3Nzg4NzQ5NDF9.NmrFjxA72Z-LFDzaIY6eDZir0yr9XksB4PiAVWROdhE

@refreshToken = 

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "passwordHash": "#Senha123"
}

###

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "abmael@eletricista.com",
  "passwordHash": "#Senha123"
}

###

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "carlos@lima.com",
  "passwordHash": "#Senha@123"
}

###

### [FALHA] Senha inválida
# Esperado: 401 UnauthorizedError
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "passwordHash": "senha-errada"
}

###

### [FALHA] E-mail inválido
# Esperado: 422 Validation Error
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "email-invalido",
  "passwordHash": "12345678"
}