@baseUrl = http://localhost:3333

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg1MzE1MTgsImV4cCI6MTc3ODU0NTkxOH0.ew-uKx1jPMYR6mp_2-cJYfMa-p6DOVCb_Ut5myfL9qA

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzc4NTMxNTE4LCJleHAiOjE3Nzg1MzI0MTh9.FqlF8VETmuzwRSVUuDvGgMJI5WuZKOa1yYWFJf6_If0

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "passwordHash": "#Senha123"
}

###

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "abmael@eletricista.com",
  "passwordHash": "#Senha123"
}

###

### [FALHA] Senha inválida
# Esperado: 401 UnauthorizedError
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "passwordHash": "senha-errada"
}

###

### [FALHA] E-mail inválido
# Esperado: 422 Validation Error
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "email-invalido",
  "passwordHash": "12345678"
}