@baseUrl = http://localhost:3333

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJhY2Nlc3MiLCJpYXQiOjE3Nzg1MTMwMDQsImV4cCI6MTc3ODUyNzQwNH0.ZCFvcr-BSjYLgkLRwe_xw6DYxgZ7I1J1b8F5iCdVo1c

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZDFkYzYzOS04Y2I2LTQzMmUtODJlNC1mMjBlYzQ1OWFjYTAiLCJpZCI6IjlkMWRjNjM5LThjYjYtNDMyZS04MmU0LWYyMGVjNDU5YWNhMCIsIm5hbWUiOiJBYm1hZWwgTWl0byBUcm9uY28iLCJlbWFpbCI6ImFibWFlbEBlbGV0cmljaXN0YS5jb20iLCJ0b2tlblR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzc4NTEzMDA0LCJleHAiOjE3Nzg1MTM5MDR9.5kLt-nllwgmyeUxk_5pPG43xbW4Vmd996MywGzx0cWk

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "passwordHash": "#Senha123"
}

###

### [SUCESSO] Login com credenciais válidas
# Esperado: 200 com accessToken, refreshToken e dados públicos do prestador
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "abmael@eletricista.com",
  "passwordHash": "#Senha123"
}

###

### [FALHA] Senha inválida
# Esperado: 401 UnauthorizedError
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "joao@barbearia.com",
  "passwordHash": "senha-errada"
}

###

### [FALHA] E-mail inválido
# Esperado: 422 Validation Error
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "email-invalido",
  "passwordHash": "12345678"
}